% =========================================================================
%  NAV_EQUATIONS - Nonlinear navigation mechanics + Jacobians
% =========================================================================
%  Implements the continuous-time navigation equations for a 13-state
%  INS model driven by IMU measurements.  Returns the state derivative
%  and, optionally, the full Jacobians A and B used by the EKF.
%
%  STATE VECTOR (13x1):
%    x(1:3)   = [pn, pe, pd]   NED position [m]
%    x(4:6)   = [u,  v,  w]   body-frame velocity [m/s]
%    x(7:10)  = [e0,e1,e2,e3] unit quaternion (body←NED)
%    x(11:13) = [bp,bq,br]    gyroscope bias [rad/s]
%
%  IMU INPUT (6x1):
%    u_imu(1:3) = y_gyro   gyroscope measurement [rad/s]
%    u_imu(4:6) = y_accel  accelerometer measurement [m/s^2]
%
%  NAVIGATION EQUATIONS:
%    ṗ        = R_vb * v_body                    (position kinematics)
%    v̇_body  = -ω_c × v_body + y_accel + g_body  (Newton, body frame)
%    q̇        = 0.5 * Ξ(q) * ω_c                (quaternion kinematics)
%    ḃ        = 0                                 (bias — random walk)
%
%    where:
%      ω_c     = y_gyro − b              (bias-corrected angular rate)
%      R_bv    = quaternion_to_rotation(q)  (body←NED)
%      R_vb    = R_bv'                      (NED←body)
%      g_body  = R_bv * [0; 0; g]          (gravity in body frame)
%      Ξ(q)    = 4×3 quaternion drive matrix
%
%  JACOBIAN A = ∂f/∂x  (13×13):
%    Analytically derived block-by-block (see derivation below).
%
%  JACOBIAN B = ∂f/∂u_imu  (13×6):
%    Analytically derived.  Used to build process noise Q = B*Q_imu*B'.
%
%  Inputs:
%    x        [13x1] current state estimate
%    u_imu    [6x1]  [y_gyro; y_accel]
%    params   struct  mav_params() (needs .gravity)
%
%  Outputs:
%    xdot     [13x1] state derivative
%    A        [13x13] ∂f/∂x  Jacobian  (omitted if nargout < 2)
%    B        [13x6]  ∂f/∂u  Jacobian  (omitted if nargout < 3)
%
%  Usage:
%    xdot = nav_equations(x, u_imu, params);
%    [xdot, A] = nav_equations(x, u_imu, params);
%    [xdot, A, B] = nav_equations(x, u_imu, params);
%
%  Author : AtlasFC
%  Ref    : Beard & McLain, "Small Unmanned Aircraft", Ch. 8
%           Groves, "Principles of GNSS, Inertial, and Multisensor
%           Integrated Navigation Systems", Ch. 14
% =========================================================================

function [xdot, A, B] = nav_equations(x, u_imu, params)

    g = params.gravity;

    % -----------------------------------------------------------------------
    %  Unpack state
    % -----------------------------------------------------------------------
    vb = x(4:6);           % body velocity [u; v_b; w]
    q  = x(7:10);          % quaternion [e0; e1; e2; e3]
    b  = x(11:13);         % gyro bias

    e0 = q(1);  e1 = q(2);  e2 = q(3);  e3 = q(4);
    u_ = vb(1); v_ = vb(2); w_ = vb(3);

    % -----------------------------------------------------------------------
    %  Unpack IMU
    % -----------------------------------------------------------------------
    y_gyro  = u_imu(1:3);
    y_accel = u_imu(4:6);

    % -----------------------------------------------------------------------
    %  Derived quantities
    % -----------------------------------------------------------------------
    R_bv    = quaternion_to_rotation(q);   % body ← NED
    R_vb    = R_bv';                       % NED  ← body

    omega_c = y_gyro - b;                  % corrected angular rate
    pc = omega_c(1);  qc = omega_c(2);  rc = omega_c(3);

    g_body  = R_bv * [0; 0; g];           % gravity in body frame

    % Ξ(q): 4×3 quaternion drive matrix  q̇ = 0.5 * Ξ * ω_c
    Xi = [ -e1, -e2, -e3;
            e0, -e3,  e2;
            e3,  e0, -e1;
           -e2,  e1,  e0 ];

    % -----------------------------------------------------------------------
    %  State derivative  f(x, u_imu)
    % -----------------------------------------------------------------------
    p_dot = R_vb * vb;
    v_dot = -cross(omega_c, vb) + y_accel + g_body;
    q_dot = 0.5 * Xi * omega_c;
    b_dot = zeros(3, 1);

    xdot  = [p_dot; v_dot; q_dot; b_dot];

    if nargout < 2, return; end

    % -----------------------------------------------------------------------
    %  Jacobian A = ∂f/∂x  (13×13)
    %
    %  Auto-generated by gen_nav_jacobians.m (Symbolic Math Toolbox).
    %  Run gen_nav_jacobians.m once to create nav_jac_A.m.
    %  To update (e.g. new state added): edit gen_nav_jacobians.m → re-run.
    %  DO NOT edit nav_jac_A.m manually.
    % -----------------------------------------------------------------------
    if isempty(which('nav_jac_A'))
        error(['nav_jac_A.m not found. ' ...
               'Run gen_nav_jacobians.m first to generate it.\n' ...
               '  >> cd core/estimator\n' ...
               '  >> run gen_nav_jacobians']);
    end
    A = nav_jac_A(x, u_imu, g);

    if nargout < 3, return; end

    % -----------------------------------------------------------------------
    %  Jacobian B = ∂f/∂u_imu  (13×6)
    %
    %  Auto-generated by gen_nav_jacobians.m (Symbolic Math Toolbox).
    %  DO NOT edit nav_jac_B.m manually.
    % -----------------------------------------------------------------------
    B = nav_jac_B(x, u_imu, g);

end
